---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-dynatrace-sli-service
  labels:
    "app": "keptn"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-dynatrace-sli-service-secrets
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-dynatrace-sli-service-secrets
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-dynatrace-sli-service-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-dynatrace-sli-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-sli-service
spec:
  selector:
    matchLabels:
      run: dynatrace-sli-service
  replicas: 1
  template:
    metadata:
      labels:
        run: dynatrace-sli-service
    spec:
      serviceAccountName: keptn-dynatrace-sli-service
      containers:
        - name: dynatrace-sli-service
          image: keptncontrib/dynatrace-sli-service:0.8.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: EVENTBROKER
              value: 'http://event-broker/keptn'
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HTTP_SSL_VERIFY
              value: 'true'
        - name: distributor
          image: keptn/distributor:0.8.0-alpha # ToDo: change to 0.8.0 once final
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.get-sli.triggered'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: dynatrace-sli-service
  labels:
    run: dynatrace-sli-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: dynatrace-sli-service
